# Setup
#
title: Rollenspiel-Lörrach
tagline: We have more fun
description: Homepage von Rollenspiel-Lörrach mit Informationen zu unseren Treffen und Terminen.

# Style/Theme/Look
#
plugins:
  - jekyll-remote-theme
remote_theme:  jekyll/minima 
minima:
  skin: dark
show_excerpts: true

# About/contact
#
author:
  #name: Hoelli
  email: "webkontakt@rollenspiel-loerrach.de"
  url: https://hoelli4c.github.io/rollenspiel-loerrach/

# Header Pages
#
header_pages:
  - info.md
  - termine.md
  - impressum.md
