# Setup
#
title: Rollenspiel-Lörrach
tagline: We have more fun
description: Homepage for Rollenspiel Lörrach.

# Theme
#
#remote_theme:  jekyll/minima 
#theme: minima
#minima:
#  skin: dark
#remote_theme: zivong/jekyll-theme-hydure
#remote_theme: poole/hyde
remote_theme: fongandrew/hydeout

# About/contact
#
author:
  name: Hoelli
  email: "webkontakt@rollenspiel-loerrach.de"
  url: https://hoelli4c.github.io/rollenspiel-loerrach/
